# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  build:
    working_directory: image
    docker:
      - image: cimg/base:current
    resource_class: arm.medium
    steps:
      - checkout
      - run:
          name: Build application Docker image
          command: |
            cd base && docker buildx build . --load --platform linux/arm64 --tag discourse/base:build_slim -f slim.Dockerfile