on:
  pull_request:
  schedule:
    - cron: "0 0 * * *"

concurrency:
  group: build-arm64-${{ format('{0}-{1}', github.head_ref || github.run_number, github.job) }}
  cancel-in-progress: true

env:
  BUILDKIT_PROGRESS: plain

jobs:
  base:
    runs-on: ubuntu-20.04
    services:
      registry:
        image: registry
        ports:
          - 5000:5000
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: build slim image
        run: |
          cd image && ruby auto_build.rb base_slim_arm64
      - name: tag slim images
        id: tag-images
        run: |
          TAG=`date +%Y%m%d-%H%M`
          echo "tag=$(echo $TAG)" >> $GITHUB_OUTPUT
          docker tag discourse/base:build_slim_arm64 discourse/base:2.0.$TAG-slim-arm64
          docker tag discourse/base:build_slim_arm64 discourse/base:slim-arm64
          docker push localhost:5000/discourse/base:build_slim_arm64
      - name: build release image
        run: |
          cd image && ruby auto_build.rb base_arm64 --build-arg from=localhost:5000/discourse/base
      - name: tag release images
        run: |
          TAG=${{ steps.tag-images.outputs.tag }}
          docker tag discourse/base:build_arm64 discourse/base:2.0.$TAG-arm64
          docker tag discourse/base:build_arm64 discourse/base:release-arm64
          docker push localhost:5000/discourse/base:build_arm64
      - name: build test_build image
        run: |
          cd image && ruby auto_build.rb discourse_test_build_arm64 --build-arg from=localhost:5000/discourse/base
      - name: run specs
        run: |
          docker run --rm -e RUBY_ONLY=1 -e USE_TURBO=1 -e SKIP_PLUGINS=1 -e SKIP_LINT=1 discourse/discourse_test:build_arm64
      - name: Print summary
        run: |
          docker images discourse/base
      - name: push to dockerhub
        if: success() && (github.ref == 'refs/heads/main')
        env:
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: |
          TAG=${{ steps.tag-images.outputs.tag }}
          docker login --username discoursebuild --password $DOCKERHUB_PASSWORD
          docker push discourse/base:2.0.$TAG-slim-arm64
          docker push discourse/base:slim-arm64
          docker tag discourse/base:slim-arm64 discourse/base:aarch64
          docker push discourse/base:2.0.$TAG-arm64
          docker push discourse/base:release-arm64
          docker push discourse/base:aarch64
  test:
    runs-on: ubuntu-20.04
    needs: base
    defaults:
      run:
        working-directory: image/discourse_test
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: build discourse/discourse_test:slim-arm64
        run: |
          docker buildx build . --load \
            --build-arg from_tag=slim-arm64 \
            --target base \
            --tag discourse/discourse_test:slim-arm64
      - name: build discourse/discourse_test:slim-browsers-arm64
        run: |
          docker buildx build . --load \
            --build-arg from_tag=slim-arm64 \
            --target with_browsers \
            --tag discourse/discourse_test:slim-browsers-arm64
      - name: build discourse/discourse_test:release-arm64
        run: |
          docker buildx build . --load \
            --build-arg from_tag=release-arm64 \
            --target release \
            --tag discourse/discourse_test:release-arm64
      - name: Print summary
        run: |
          docker images discourse/discourse_test
      - name: push to dockerhub
        if: success() && (github.ref == 'refs/heads/main')
        env:
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: |
          docker login --username discoursebuild --password $DOCKERHUB_PASSWORD
          docker push discourse/discourse_test:slim-arm64
          docker push discourse/discourse_test:slim-browsers-arm64
          docker push discourse/discourse_test:release-arm64
  dev:
    runs-on: ubuntu-20.04
    needs: base
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: build discourse/discourse_dev:release-arm64 image
        run: |
          cd image && ruby auto_build.rb discourse_dev_arm64
      - name: push to dockerhub
        if: success() && (github.ref == 'refs/heads/main')
        env:
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: |
          docker tag discourse/discourse_dev:build_arm64 discourse/discourse_dev:release-arm64
          docker login --username discoursebuild --password $DOCKERHUB_PASSWORD
          docker push discourse/discourse_dev:release-arm64
